# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Disordered Ramblings
tagline:          The rantings of a physics student, gamer and hobby programmer.
paginate:         1
baseurl:          /
author:
  name:           Solonarv
  url:            https://twitter.com/solonarv
  email:          nstamm@gmx.de

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/solonarv/solonarv.github.io
